<?php
// Generated by admin Selectel settings on 2025-11-09T19:25:56+03:00
if (!isset($inc) || !is_array($inc)) { $inc = []; }
$inc['selectel_status'] = '1';
$inc['selectel_bucket'] = 'subspark';
$inc['selectel_region'] = 'ru-1';
$inc['selectel_key'] = '21c96e9b94ed4f23adfe7f1e82e86fe4';
$inc['selectel_secret_key'] = '655c4008ea41490cbb279a0c76684548';
$inc['selectel_endpoint'] = 'https://s3.ru-1.storage.selcloud.ru';
$inc['selectel_public_base'] = 'https://6a9c6762-1a83-4aab-81a5-efefedbd168a.selstorage.ru/';
